---
- stat: path='/opt/activator-dist-{{ typesafe_activator_version }}'
  register: activatordir
  
- name: Download Typesafe Activator
  when: activatordir.stat.exists == false
  get_url: url={{ typesafe_activator_url }} dest="/tmp/{{ typesafe_activator_archive }}"
  environment: 
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{http_proxy}}"

- name: Unzip Typesafe Activator
  when: activatordir.stat.exists == false
  unarchive: copy=no src='/tmp/{{ typesafe_activator_archive }}' dest=/opt

- name: make executable
  file: >-
    path='/opt/activator-dist-{{typesafe_activator_version}}/activator'
    mode=0755
  
- name: Link Typesafe Activator
  file: src='/opt/activator-dist-{{ typesafe_activator_version }}' dest=/opt/activator state=link

- name: include activator in the PATH
  copy: >-
    src=etc/profile.d/activator.sh
    dest=/etc/profile.d/activator.sh
    mode=0644
    owner=root
    group=root
